setup: &default_setup
    api_root: http://localhost/v1/api
    proxies: {}
    users:
        - &default_user
          username: oisp@testing.com
          password: OispTesting1
          role: admin

locals: &default_locals
    dashboard_container: oisp_frontend_1
    postgres_container: oisp_postgres_1