#include configs/base.yaml

setup:
   <<: *default_setup
   users:
       - <<: *default_user
         accounts:
             - name: myacc
               devices:
                 name: mydev
                 id: mydevid
                 count: 1000

locals: *default_locals